# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Please see the documentation for all Dependabot workflow configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain Cargo dependencies for security updates
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain GitHub Actions dependencies for security updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
