# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

[package]
name = "aquariwm"
version = "0.1.0"
authors = [ "AquariWM <contact@aquariwm.org>", "Antikyth <antikyth at gmail dot com>" ]
edition = "2021"
description = """Any language, any level of experience, fully extensible. \
                 It's time for a tiling window manager everyone can use."""
readme = true
homepage = "https://aquariwm.org/"
repository = "https://github.com/AquariWM/aquariwm"
license = "MPL-2.0"
keywords = [ "x11", "window-manager", "xorg", "window", "linux" ]
categories = [ "accessibility", "config", "graphics", "gui" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "1.1.1"
