# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

[package]
name = "AquariWM"
version = "0.1.0"
authors = ["Antikyth <antikyth at gmail dot com>", "AquariWM"]
edition = "2021"
description = "The extensible user-friendly window manager."
readme = true
homepage = "https://github.com/AquariWM/AquariWM"
repository = "https://github.com/AquariWM/AquariWM"
license = "MPL-2.0"
keywords = ["window", "window-manager", "linux", "documented"]
categories = ["accessibility", "config", "graphics", "gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
